agency/urls.py
from django.urls import path

from agency.views import (
    index,
    TopicListView,
    TopicCreateView,
    TopicUpdateView,
    TopicDeleteView,
    RedactorListView,
    RedactorDetailView,
    RedactorCreateView,
    RedactorExperienceUpdateView,
    RedactorDeleteView,
    NewspaperListView,
    NewspaperDetailView,
    toggle_assign_to_newspaper,
    NewspaperCreateView,
    NewspaperUpdateView,
    NewspaperDeleteView,
)

urlpatterns = [
    path("", index, name="index"),
    path(
        "topics/",
        TopicListView.as_view(),
        name="topic-list",
    ),
    path(
        "topics/create/",
        TopicCreateView.as_view(),
        name="topic-create",
    ),
    path(
        "topics/<int:pk>/update/",
        TopicUpdateView.as_view(),
        name="topic-update",
    ),
    path(
        "topics/<int:pk>/delete/",
        TopicDeleteView.as_view(),
        name="topic-delete",
    ),
    path(
        "redactors/",
        RedactorListView.as_view(),
        name="redactor-list",
    ),
    path("redactors/<int:pk>/", RedactorDetailView.as_view(), name="redactor-detail"),
    path(
        "redactors/create/",
        RedactorCreateView.as_view(),
        name="redactor-create",
    ),
    path(
        "redactors/<int:pk>/update/",
        RedactorExperienceUpdateView.as_view(),
        name="redactor-update",
    ),
    path(
        "redactors/<int:pk>/delete/",
        RedactorDeleteView.as_view(),
        name="redactor-delete",
    ),
    path(
        "newspapers/",
        NewspaperListView.as_view(),
        name="newspaper-list",
    ),
    path(
        "newspapers/<int:pk>/", NewspaperDetailView.as_view(), name="newspaper-detail"
    ),
    path("newspapers/create/", NewspaperCreateView.as_view(), name="newspaper-create"),
    path(
        "newspapers/<int:pk>/update/",
        NewspaperUpdateView.as_view(),
        name="newspaper-update",
    ),
    path(
        "newspapers/<int:pk>/delete/",
        NewspaperDeleteView.as_view(),
        name="newspaper-delete",
    ),
    path(
        "newspapers/<int:pk>/toggle-assign/",
        toggle_assign_to_newspaper,
        name="toggle-newspaper-assign",
    ),
]

app_name = "agency"

newspaper_agency/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("agency.urls", namespace="agency")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
    path("djrichtextfield/", include("djrichtextfield.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

agency/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.urls import reverse
from ckeditor.fields import RichTextField


class Topic(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ["id"]

    def __str__(self):
        return self.name


class Redactor(AbstractUser):
    years_of_experience = models.IntegerField()

    class Meta:
        ordering = ["id"]

    def __str__(self):
        return f"{self.username} ({self.first_name} {self.last_name})"

    def get_absolute_url(self):
        return reverse("agency:redactor-detail", kwargs={"pk": self.pk})


class Newspaper(models.Model):
    title = models.CharField(max_length=255)
    content = RichTextField()
    published_date = models.DateTimeField(auto_now_add=True)
    topic = models.ForeignKey(
        Topic, on_delete=models.CASCADE, related_name="newspapers"
    )
    publishers = models.ManyToManyField(Redactor, related_name="newspapers")

    class Meta:
        ordering = ["id"]

    def __str__(self):
        return f"{self.title} ({self.topic})"

agency/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

from agency.models import Newspaper
from agency.validators import validate_years_of_experience


class TopicSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by name.."}),
    )


class RedactorCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = UserCreationForm.Meta.fields + (
            "years_of_experience",
            "first_name",
            "last_name",
        )

    def clean_years_of_experience(self):
        return validate_years_of_experience(self.cleaned_data["years_of_experience"])


class RedactorExperienceUpdateForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ["years_of_experience"]

    def clean_years_of_experience(self):
        return validate_years_of_experience(self.cleaned_data["years_of_experience"])


class RedactorSearchForm(forms.Form):
    username = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by username.."}),
    )


class NewspaperForm(forms.ModelForm):
    publishers = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )

    class Meta:
        model = Newspaper
        fields = "__all__"


class NewspaperSearchForm(forms.Form):
    title = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by title.."}),
    )

agency/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from agency.forms import (
    TopicSearchForm,
    RedactorSearchForm,
    RedactorCreationForm,
    RedactorExperienceUpdateForm,
    NewspaperSearchForm,
    NewspaperForm,
)
from agency.models import Redactor, Newspaper, Topic


@login_required
def index(request):
    num_redactors = Redactor.objects.count()
    num_newspapers = Newspaper.objects.count()
    num_topics = Topic.objects.count()

    context = {
        "num_redactors": num_redactors,
        "num_newspapers": num_newspapers,
        "num_topics": num_topics,
    }

    return render(request, "agency/index.html", context=context)


class TopicListView(LoginRequiredMixin, generic.ListView):
    model = Topic
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(TopicListView, self).get_context_data(**kwargs)

        name = self.request.GET.get("name", "")

        context["search_form"] = TopicSearchForm(initial={"name": name})

        return context

    def get_queryset(self):
        queryset = Topic.objects.all()

        form = TopicSearchForm(self.request.GET)

        if form.is_valid():
            return queryset.filter(name__icontains=form.cleaned_data["name"])

        return queryset


class TopicCreateView(LoginRequiredMixin, generic.CreateView):
    model = Topic
    fields = "__all__"
    success_url = reverse_lazy("agency:topic-list")


class TopicUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Topic
    fields = "__all__"
    success_url = reverse_lazy("agency:topic-list")


class TopicDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Topic
    success_url = reverse_lazy("agency:topic-list")


class RedactorListView(LoginRequiredMixin, generic.ListView):
    model = get_user_model()
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(RedactorListView, self).get_context_data(**kwargs)

        username = self.request.GET.get("username", "")

        context["search_form"] = RedactorSearchForm(initial={"username": username})

        return context

    def get_queryset(self):
        queryset = get_user_model().objects.all()

        form = RedactorSearchForm(self.request.GET)

        if form.is_valid():
            return queryset.filter(username__icontains=form.cleaned_data["username"])

        return queryset


class RedactorDetailView(LoginRequiredMixin, generic.DetailView):
    model = get_user_model()
    queryset = get_user_model().objects.all().prefetch_related("newspapers__topic")


class RedactorCreateView(LoginRequiredMixin, generic.CreateView):
    model = get_user_model()
    form_class = RedactorCreationForm


class RedactorExperienceUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = get_user_model()
    form_class = RedactorExperienceUpdateForm
    success_url = reverse_lazy("agency:redactor-list")


class RedactorDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = get_user_model()
    success_url = reverse_lazy("agency:redactor-list")


class NewspaperListView(LoginRequiredMixin, generic.ListView):
    model = Newspaper
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(NewspaperListView, self).get_context_data(**kwargs)

        title = self.request.GET.get("title", "")

        context["search_form"] = NewspaperSearchForm(initial={"title": title})

        return context

    def get_queryset(self):
        queryset = Newspaper.objects.select_related("topic")

        form = NewspaperSearchForm(self.request.GET)

        if form.is_valid():
            return queryset.filter(title__icontains=form.cleaned_data["title"])

        return queryset


class NewspaperDetailView(LoginRequiredMixin, generic.DetailView):
    model = Newspaper


class NewspaperCreateView(LoginRequiredMixin, generic.CreateView):
    model = Newspaper
    form_class = NewspaperForm
    success_url = reverse_lazy("agency:newspaper-list")


class NewspaperUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Newspaper
    form_class = NewspaperForm
    success_url = reverse_lazy("agency:newspaper-list")


class NewspaperDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Newspaper
    success_url = reverse_lazy("agency:newspaper-list")


@login_required
def toggle_assign_to_newspaper(request, pk):
    redactor = get_user_model().objects.get(id=request.user.id)
    if Newspaper.objects.get(id=pk) in redactor.newspapers.all():
        redactor.newspapers.remove(pk)
    else:
        redactor.newspapers.add(pk)
    return HttpResponseRedirect(reverse_lazy("agency:newspaper-detail", args=[pk]))

templates/agency/index.html
{% extends "layouts/base.html" %}

{% block title %} Home {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block body_class %} index-page {% endblock body_class %}

{% block content %}

{% include 'includes/header.html' %}

<section class="pt-5 pb-4" id="count-stats">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 z-index-2 border-radius-xl mt-n10 mx-auto py-3 blur shadow-blur">
        <div class="row">
          <div class="col-md-4 position-relative">
            <div class="p-3 text-center">
              <h1 class="text-gradient text-primary" id="state1" countTo="{{ num_topics }}">0</h1>
              <h5 class="mt-3"><a href="{% url 'agency:topic-list' %}">Topics</a></h5>
              <p class="text-sm">Click here to see the list of all topics that are available in the Newspaper Agency</p>
            </div>
            <hr class="vertical dark">
          </div>
          <div class="col-md-4 position-relative">
            <div class="p-3 text-center">
              <h1 class="text-gradient text-primary" id="state2" countTo="{{ num_newspapers }}">0</h1>
              <h5 class="mt-3"><a href="{% url 'agency:newspaper-list' %}">Newspapers</a></h5>
              <p class="text-sm">Click here to see the list of all newspapers that are available in the Newspaper Agency</p>
            </div>
            <hr class="vertical dark">
          </div>
          <div class="col-md-4">
            <div class="p-3 text-center">
              <h1 class="text-gradient text-primary" id="state3" countTo="{{ num_redactors }}">0</h1>
              <h5 class="mt-3"><a href="{% url 'agency:redactor-list' %}">Redactors</a></h5>
              <p class="text-sm">Click here to see the list of all redactors that are available in the Newspaper Agency</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock content %}

<!-- Specific JS goes HERE -->
{% block javascripts %}

<script src="{{ ASSETS_ROOT }}/js/plugins/countup.min.js"></script>
<script src="{{ ASSETS_ROOT }}/js/plugins/choices.min.js"></script>
<script src="{{ ASSETS_ROOT }}/js/plugins/rellax.min.js"></script>
<script src="{{ ASSETS_ROOT }}/js/plugins/tilt.min.js"></script>
<script src="{{ ASSETS_ROOT }}/js/plugins/choices.min.js"></script>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDTTfWur0PDbZWPr7Pmq8K3jiDp0_xUziI"></script>
<script src="{{ ASSETS_ROOT }}/js/soft-design-system.min.js?v=1.0.1" type="text/javascript"></script>
<script type="text/javascript">
  if (document.getElementById('state1')) {
    const countUp = new CountUp('state1', document.getElementById("state1").getAttribute("countTo"));
    if (!countUp.error) {
      countUp.start();
    } else {
      console.error(countUp.error);
    }
  }
  if (document.getElementById('state2')) {
    const countUp1 = new CountUp('state2', document.getElementById("state2").getAttribute("countTo"));
    if (!countUp1.error) {
      countUp1.start();
    } else {
      console.error(countUp1.error);
    }
  }
  if (document.getElementById('state3')) {
    const countUp2 = new CountUp('state3', document.getElementById("state3").getAttribute("countTo"));
    if (!countUp2.error) {
      countUp2.start();
    } else {
      console.error(countUp2.error);
    };
  }
</script>

{% endblock javascripts %}

templates/agency/newspaper_confirm_delete.html
{% extends "layouts/base.html" %}
{% load i18n %}

{% block content %}

{% include 'includes/header.html' %}

<section class="pt-5 pb-4" id="count-stats">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 z-index-2 border-radius-xl mt-n10 mx-auto py-3 blur shadow-blur">
        <h1>Delete newspaper "{{ newspaper.title }}"?</h1>
        <form action="" method="post">
          {% csrf_token %}

          <input type="submit" value="{% trans 'Confirm deletion' %}" class="btn btn-danger">
          <input type="submit" value="{% trans 'Cancel' %}" class="btn btn-secondary">
        </form>
      </div>
    </div>
  </div>
</section>

{% endblock %}

templates/agency/newspaper_detail.html
{% extends "layouts/base.html" %}

{% block content %}

{% include 'includes/header.html' %}

<section class="pt-5 pb-4" id="count-stats">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 z-index-2 border-radius-xl mt-n10 mx-auto py-3 blur shadow-blur">
        <h1>
          {{ newspaper.title }}
          <a href="{% url 'agency:newspaper-update' pk=newspaper.id %}" class="btn btn-secondary link-to-page">
            Update
          </a>

          <a href="{% url 'agency:newspaper-delete' pk=newspaper.id %}" class="btn btn-danger link-to-page">
            Delete
          </a>

        </h1>
        <p><h4>Topic: {{ newspaper.topic.name }}</h4></p>

        <div style="text-align: justify">{{ newspaper.content|safe }}</div>

        <h1>
          Publishers

          {% if newspaper in user.newspapers.all %}
            <a href="{% url 'agency:toggle-newspaper-assign' pk=newspaper.id %}" class="btn btn-danger link-to-page">
              Delete me from this newspaper
            </a>
          {% else %}
            <a href="{% url 'agency:toggle-newspaper-assign' pk=newspaper.id %}" class="btn btn-success link-to-page">
              Assign me to this newspaper
            </a>
          {% endif %}

        </h1>
        <hr>
        <ul>
          {% for newspaper in newspaper.publishers.all %}
            <li>{{ newspaper.username }} ({{ newspaper.first_name }} {{ newspaper.last_name }})</li>
          {% endfor %}
        </ul>
      {% endblock %}
      </div>
    </div>
  </div>
</section>

templates/agency/newspaper_form.html
{% extends "layouts/base.html" %}
{% load crispy_forms_filters %}

{% block content %}

{% include 'includes/header.html' %}

<section class="pt-5 pb-4" id="count-stats">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 z-index-2 border-radius-xl mt-n10 mx-auto py-3 blur shadow-blur">
        <h1>{{ object|yesno:"Update,Create" }} newspaper</h1>
        <form action="" method="post" novalidate>
          {% csrf_token %}
          {{ form|crispy }}

          <input type="submit" value="Submit" class="btn btn-primary">
        </form>
      </div>
    </div>
  </div>
</section>

{% endblock %}

templates/agency/newspaper_list.html
{% extends "layouts/base.html" %}
{% load crispy_forms_filters %}

{% block content %}

{% include 'includes/header.html' %}

<section class="pt-5 pb-4" id="count-stats">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 z-index-2 border-radius-xl mt-n10 mx-auto py-3 blur shadow-blur">
        <h1>
          Newspapers
          <a href="{% url 'agency:newspaper-create' %}" class="btn btn-primary link-to-page">
            Create
          </a>
        </h1>

        <form action="" method="get" class="form-inline">
          {{ search_form|crispy }}
          <input class="btn btn-secondary" type="submit" value="🔎">
        </form>

        {% if newspaper_list %}
          <table class="table">
            <tr>
              <th>ID</th>
              <th>Title</th>
              <th>Topic</th>
              <th>Published date</th>
            </tr>
          {% for newspaper in newspaper_list %}
            <tr>
              <td>{{ newspaper.id }}</td>
              <td><a href="{% url 'agency:newspaper-detail' pk=newspaper.id %}">{{ newspaper.title }}</a></td>
              <td>{{ newspaper.topic.name }}</td>
              <td>{{ newspaper.published_date }}</td>
            </tr>
          {% endfor %}
          </table>
        {% else %}
          <p>There are no newspapers in agency</p>
        {% endif %}

      </div>
    </div>
  </div>
</section>

{% endblock %}

templates/agency/redactor_confirm_delete.html
{% extends "layouts/base.html" %}
{% load i18n %}

{% block content %}

{% include 'includes/header.html' %}

<section class="pt-5 pb-4" id="count-stats">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 z-index-2 border-radius-xl mt-n10 mx-auto py-3 blur shadow-blur">
        <h1>Delete redactor {{ redactor.username }}?</h1>
        <form action="" method="post">
          {% csrf_token %}

          <input type="submit" value="{% trans 'Confirm deletion' %}" class="btn btn-danger">
          <input type="submit" value="{% trans 'Cancel' %}" class="btn btn-secondary">
        </form>
      </div>
    </div>
  </div>
</section>

{% endblock %}

templates/agency/redactor_detail.html
{% extends "layouts/base.html" %}

{% block content %}

{% include 'includes/header.html' %}

<section class="pt-5 pb-4" id="count-stats">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 z-index-2 border-radius-xl mt-n10 mx-auto py-3 blur shadow-blur">
        <h1>
          Username: {{ redactor.username }}

          <a href="{% url 'agency:redactor-update' pk=redactor.id %}" class="btn btn-secondary link-to-page">
            Update years of experience
          </a>

          <a href="{% url 'agency:redactor-delete' pk=redactor.id %}" class="btn btn-danger link-to-page">
            Delete
          </a>
        </h1>

        <p><strong>First name:</strong> {{ redactor.first_name }}</p>
        <p><strong>Last name:</strong> {{ redactor.last_name }}</p>
        <p><strong>Years of experience:</strong> {{ redactor.years_of_experience }}</p>
        <p><strong>Is staff:</strong> {{ redactor.is_staff }}</p>

        <div class="ml-3">
          <h4>Newspapers</h4>

          {% for newspaper in redactor.newspapers.all %}
              <hr>
              <p><strong>Title:</strong> <a href="{% url 'agency:newspaper-detail' pk=newspaper.id %}">{{ newspaper.title }}</a></p>
              <p><strong>Topic:</strong> {{ newspaper.topic.name }}</p>
              <p class="text-muted"><strong>Id:</strong> {{newspaper.id}}</p>

          {% empty %}
            <p>No newspapers!</p>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock %}

templates/agency/redactor_form.html
{% extends "layouts/base.html" %}
{% load crispy_forms_filters %}

{% block content %}

{% include 'includes/header.html' %}

<section class="pt-5 pb-4" id="count-stats">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 z-index-2 border-radius-xl mt-n10 mx-auto py-3 blur shadow-blur">
        <h1>{{ object|yesno:"Update,Create" }} redactor</h1>
        <form action="" method="post" novalidate>
          {% csrf_token %}
          {{ form|crispy }}

          <input type="submit" value="Submit" class="btn btn-primary">
        </form>
      </div>
    </div>
  </div>
</section>

{% endblock %}

templates/agency/redactor_list.html
{% extends "layouts/base.html" %}
{% load crispy_forms_filters %}

{% block content %}

{% include 'includes/header.html' %}

<section class="pt-5 pb-4" id="count-stats">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 z-index-2 border-radius-xl mt-n10 mx-auto py-3 blur shadow-blur">
        <h1>
          Redactors
          <a href="{% url 'agency:redactor-create' %}" class="btn btn-primary link-to-page">
            Create
          </a>
        </h1>

        <form action="" method="get" class="form-inline">
          {{ search_form|crispy }}
          <input class="btn btn-secondary" type="submit" value="🔎">
        </form>

        {% if redactor_list %}
        <table class="table">
          <tr>
            <th>ID</th>
            <th>Username</th>
            <th>First name</th>
            <th>Last name</th>
            <th>Years of experience</th>
          </tr>
        {% for redactor in redactor_list %}
          <tr>
            <td>{{ redactor.id }}</td>
            <td><a href="{{ redactor.get_absolute_url }}">{{ redactor.username }} {% if user == redactor %} (Me){% endif %}</a></td>
            <td>{{ redactor.first_name }}</td>
            <td>{{ redactor.last_name }}</td>
            <td>{{ redactor.years_of_experience }}</td>
          </tr>
        {% endfor %}

        </table>
        {% else %}
          <p>There are no redactors in the agency.</p>
        {% endif %}
      </div>
    </div>
  </div>
</section>
{% endblock %}

templates/agency/topic_confirm_delete.html
{% extends "layouts/base.html" %}
{% load i18n %}

{% block content %}

{% include 'includes/header.html' %}

<section class="pt-5 pb-4" id="count-stats">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 z-index-2 border-radius-xl mt-n10 mx-auto py-3 blur shadow-blur">
        <h1>Delete topic {{ topic.name }}?</h1>
        <form action="" method="post">
          {% csrf_token %}

          <input type="submit" value="{% trans 'Confirm deletion' %}" class="btn btn-danger">
          <input type="submit" value="{% trans 'Cancel' %}" class="btn btn-secondary">
        </form>
      </div>
    </div>
  </div>
</section>

{% endblock %}

templates/agency/topic_form.html
{% extends "layouts/base.html" %}
{% load crispy_forms_filters %}

{% block content %}

{% include 'includes/header.html' %}

<section class="pt-5 pb-4" id="count-stats">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 z-index-2 border-radius-xl mt-n10 mx-auto py-3 blur shadow-blur">
        <h1>{{ object|yesno:"Update,Create" }} Topic</h1>
        <form action="" method="post" novalidate>
          {% csrf_token %}
          {{ form|crispy }}

          <input type="submit" value="Submit" class="btn btn-primary">
        </form>
      </div>
    </div>
  </div>
</section>

{% endblock %}

templates/agency/topic_list.html
{% extends "layouts/base.html" %}
{% load crispy_forms_filters %}

{% block content %}

{% include 'includes/header.html' %}

<section class="pt-5 pb-4" id="count-stats">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 z-index-2 border-radius-xl mt-n10 mx-auto py-3 blur shadow-blur">
        <h1>
          Topics
          <a href="{% url 'agency:topic-create' %}" class="btn btn-primary link-to-page">
            Create
          </a>
        </h1>

        <form action="" method="get" class="form-inline">
          {{ search_form|crispy }}
          <input class="btn btn-secondary" type="submit" value="🔎">
        </form>

        {% if topic_list %}
          <table class="table">
            <tr>
              <th>ID</th>
              <th>Name</th>
              <th>Update</th>
              <th>Delete</th>
            </tr>

            {% for topic in topic_list %}
              <tr>
                <td>
                    {{ topic.id }}
                </td>
                <td>
                    {{ topic.name }}
                </td>
                <td>
                    <a href="{% url 'agency:topic-update' pk=topic.id %}">
                      Update
                    </a>
                  </td>
                  <td>
                    <a style="color: red"
                      href="{% url 'agency:topic-delete' pk=topic.id %}">
                      Delete
                    </a>
                  </td>
              </tr>
            {% endfor %}
          </table>

        {% else %}
            <p>There are no topics in the agency.</p>
        {% endif %}
      </div>
    </div>
  </div>
</section>


{% endblock %}